 require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pushapp' do
  config = use_native_modules!
  pod 'PushIOManager', :path => './PushIOManager'	

  use_react_native!(:path => config["reactNativePath"])

  target 'pushappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.74.0')


  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if Gem::Version.new('11.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end
end

target 'pushapp-tvOS' do
  # Pods for pushapp-tvOS

  target 'pushapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
